# Capstone Project 4: AI-Based Recommendation System

## Objective

The objective of this project is to build a movie recommendation system using content-based filtering.

The system recommends similar movies based on movie genres.

# Business Problem

Streaming platforms contain thousands of movies.

Users often struggle to find movies they may enjoy.

A recommendation system helps users discover similar content based on their interests.

# Project Workflow

1. Import Libraries
2. Load Dataset
3. Data Preparation
4. Pattern Learning
5. Recommendation Logic
6. Evaluation
7. Business Insights

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import warnings
warnings.filterwarnings("ignore")

In [2]:
movies = pd.read_csv("../data/movies.csv")

ratings = pd.read_csv("../data/ratings.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

# Dataset Overview

The dataset contains:

- Movie ID
- Movie Title
- Genres
- User Ratings

Movie genres will be used to build a content-based recommendation system.

# Pattern Learning

Movie genres are converted into numerical features using CountVectorizer.

This allows the recommendation system to learn similarities between movies.

In [6]:
movies["genres"] = movies["genres"].fillna("")

In [7]:
vectorizer = CountVectorizer(token_pattern=r"[^|]+")

genre_matrix = vectorizer.fit_transform(movies["genres"])

In [8]:
genre_matrix.shape

(9742, 20)

In [9]:
similarity = cosine_similarity(genre_matrix)

In [10]:
similarity.shape

(9742, 9742)

# Recommendation Logic

A function is created to recommend similar movies based on genre similarity.

In [11]:
indices = pd.Series(
    movies.index,
    index=movies["title"]
).drop_duplicates()

In [12]:
def recommend_movies(title, n=5):

    if title not in indices:
        return "Movie not found."

    idx = indices[title]

    scores = list(enumerate(similarity[idx]))

    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )

    scores = scores[1:n+1]

    movie_indices = [i[0] for i in scores]

    return movies["title"].iloc[movie_indices]

In [13]:
recommend_movies("Toy Story (1995)")

1706                                       Antz (1998)
2355                                Toy Story 2 (1999)
2809    Adventures of Rocky and Bullwinkle, The (2000)
3000                  Emperor's New Groove, The (2000)
3568                             Monsters, Inc. (2001)
Name: title, dtype: object

In [14]:
recommend_movies("Matrix, The (1999)")

68           Screamers (1995)
144    Johnny Mnemonic (1995)
296         Virtuosity (1995)
336            Timecop (1994)
474       Blade Runner (1982)
Name: title, dtype: object

# Evaluation Strategy

The recommendation system is evaluated by checking whether the recommended movies belong to similar genres.

Although no prediction accuracy metric is used, the recommendations should be relevant based on movie genres.

In [15]:
movie = "Toy Story (1995)"

print("Recommendations for:", movie)

recommend_movies(movie)

Recommendations for: Toy Story (1995)

1706                                       Antz (1998)
2355                                Toy Story 2 (1999)
2809    Adventures of Rocky and Bullwinkle, The (2000)
3000                  Emperor's New Groove, The (2000)
3568                             Monsters, Inc. (2001)
Name: title, dtype: object

In [16]:
movie = "Matrix, The (1999)"

print("Recommendations for:", movie)

recommend_movies(movie)

Recommendations for: Matrix, The (1999)

68           Screamers (1995)
144    Johnny Mnemonic (1995)
296         Virtuosity (1995)
336            Timecop (1994)
474       Blade Runner (1982)
Name: title, dtype: object

# Business Insights

A recommendation system helps users discover movies that match their interests.

Benefits include:

- Personalized recommendations
- Increased user engagement
- Higher watch time
- Improved customer satisfaction
- Better content discovery

# Conclusion

This project demonstrated a content-based recommendation system using movie genres.

The recommendation engine learns patterns from movie genres and suggests similar movies using cosine similarity.

In [17]:
sample_recommendations = recommend_movies("Toy Story (1995)")

sample_recommendations.to_csv(
    "../outputs/sample_recommendations.csv",
    index=False
)

In [18]:
genre_counts = movies["genres"].str.split("|").explode().value_counts().head(10)

plt.figure(figsize=(10,5))

genre_counts.plot(kind="bar")

plt.title("Top Movie Genres")

plt.ylabel("Count")

plt.tight_layout()

plt.savefig("../images/top_genres.png")

plt.show()

NameError: name 'plt' is not defined